spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/orderdb
    username: postgres
    password: 1
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
